// src/modules/public/how-it-works/config.ts
import { RoleGuide, FaqItem } from "./types";

export const ROLE_GUIDES: Record<string, RoleGuide> = {
  employee: {
    roleKey: "employee",
    tabLabel: "Employee / Job Seeker",
    badgeText: "For Job Seekers & Freelancers",
    heading: "Build Your Verified Career Journey",
    introduction: "Discover verified job opportunities, showcase your credentials, and track application progress from submission to hire.",
    accentColor: "text-blue-600 dark:text-blue-400",
    bgAccent: "bg-blue-50 dark:bg-blue-950/30",
    borderAccent: "border-blue-200 dark:border-blue-800",
    totalOnboardingTime: "~5 mins total setup",
    oneSentenceSummary: "Create your profile, apply for verified jobs, and track every application step-by-step.",
    finalCtaTitle: "Ready to Accelerate Your Career?",
    finalCtaSubtitle: "Join thousands of job seekers connected with top verified employers across the Philippines.",
    finalCtaLabel: "Create an Employee Account",
    finalCtaRoute: "/signup?role=employee",
    steps: [
      {
        stepNumber: 1,
        title: "Create Your Account",
        statusChip: "Registration",
        estimatedTime: "⏱ 2–3 minutes",
        description: "Enter personal and login information and select Employee as your primary account type.",
        outcome: "Establish your secure credentials to access the candidate dashboard and profile builder.",
        requirements: [
          "Use an active email address or mobile number",
          "Create a secure password (at least 8 characters)",
          "Review and accept the Terms and Privacy Policy",
        ],
        actionLabel: "Create Employee Account",
        actionRoute: "/signup?role=employee",
        illustrationSrc: "/illustrations/how-it-works/employee/register.svg",
        illustrationAlt: "Employee completing VOS Sync account registration",
      },
      {
        stepNumber: 2,
        title: "Verify Your Account",
        statusChip: "Authentication",
        estimatedTime: "⏱ Less than 1 minute",
        description: "Confirm your registered email address or mobile number using the one-time password sent by VOS Sync.",
        outcome: "Activate your account security and unlock full access to profile setup features.",
        requirements: [
          "Enter the 6-digit OTP code before it expires",
          "Use resend code only when necessary",
          "Successful OTP verification unlocks onboarding",
        ],
        actionLabel: "Verify Account",
        illustrationSrc: "/illustrations/how-it-works/employee/verify.svg",
        illustrationAlt: "Employee entering security verification code",
      },
      {
        stepNumber: 3,
        title: "Complete Your Profile",
        statusChip: "Profile Setup",
        estimatedTime: "⏱ 10 minutes",
        description: "Add the information employers need to understand your background, skills, and job preferences.",
        outcome: "Build an attractive, comprehensive profile that stands out to hiring managers.",
        requirements: [
          "Personal details and contact information",
          "Education and employment history",
          "Skills, job preferences, and preferred location",
        ],
        actionLabel: "Complete Profile",
        illustrationSrc: "/illustrations/how-it-works/employee/profile.svg",
        illustrationAlt: "Employee building candidate profile and adding skills",
      },
      {
        stepNumber: 4,
        title: "Upload Your Resume and Documents",
        statusChip: "Document Upload",
        estimatedTime: "⏱ 3–5 minutes",
        description: "Submit a résumé and supporting records required for profile and identity verification.",
        outcome: "Provide verifiable proof of qualifications so employers can review your credentials with confidence.",
        requirements: [
          "Résumé or Curriculum Vitae (PDF/Docx)",
          "Government ID or professional certifications",
          "Readable files in accepted formats and sizes",
        ],
        actionLabel: "Upload Documents",
        illustrationSrc: "/illustrations/how-it-works/employee/upload.svg",
        illustrationAlt: "Employee uploading resume and verification documents",
      },
      {
        stepNumber: 5,
        title: "Browse Available Jobs",
        statusChip: "Job Search",
        estimatedTime: "⏱ Ongoing",
        description: "Explore verified opportunities and narrow down results using relevant location, setup, and category filters.",
        outcome: "Find positions perfectly matched to your skills, experience, and salary expectations.",
        requirements: [
          "Search by keyword or job title",
          "Filter by location, work setup (Remote/On-site), or salary",
          "Open job cards to review complete details",
        ],
        actionLabel: "Browse Jobs",
        actionRoute: "/find-jobs",
        illustrationSrc: "/illustrations/how-it-works/employee/browse.svg",
        illustrationAlt: "Employee searching verified jobs with location filters",
      },
      {
        stepNumber: 6,
        title: "Apply and Track Applications",
        statusChip: "Application",
        estimatedTime: "⏱ 1 minute per application",
        description: "Submit suitable applications and monitor each application from review through interview and selection.",
        outcome: "Stay informed with real-time application updates and direct interview scheduling.",
        requirements: [
          "Confirm application information before submission",
          "Answer screening questions when required",
          "Check application status and notifications regularly",
        ],
        actionLabel: "View Job Opportunities",
        actionRoute: "/find-jobs",
        illustrationSrc: "/illustrations/how-it-works/employee/apply.svg",
        illustrationAlt: "Employee tracking job application status timeline",
      },
    ],
  },
  employer: {
    roleKey: "employer",
    tabLabel: "Employer / Company",
    badgeText: "For Employers & Companies",
    heading: "Recruit Verified Professional Talent",
    introduction: "Verify your business, publish job openings, screen qualified applicants, and streamline your hiring pipeline.",
    accentColor: "text-emerald-600 dark:text-emerald-400",
    bgAccent: "bg-emerald-50 dark:bg-emerald-950/30",
    borderAccent: "border-emerald-200 dark:border-emerald-800",
    totalOnboardingTime: "~10 mins setup + review",
    oneSentenceSummary: "Register your company, verify credentials, publish vacancies, and hire top candidates.",
    finalCtaTitle: "Ready to Hire Verified Talent?",
    finalCtaSubtitle: "Start posting jobs and connecting with qualified professionals today.",
    finalCtaLabel: "Register Your Company",
    finalCtaRoute: "/signup?role=employer",
    steps: [
      {
        stepNumber: 1,
        title: "Create Your Account",
        statusChip: "Employer Sign Up",
        estimatedTime: "⏱ 3 minutes",
        description: "Register as an Employer using the authorized company representative's contact and login information.",
        outcome: "Establish your company administrator account and access the employer dashboard.",
        requirements: [
          "Use a company-managed email address when available",
          "Identify the authorized company representative",
          "Accept platform Terms and Privacy Policy",
        ],
        actionLabel: "Create Employer Account",
        actionRoute: "/signup?role=employer",
        illustrationSrc: "/illustrations/how-it-works/employer/register.svg",
        illustrationAlt: "Company representative registering an employer account",
      },
      {
        stepNumber: 2,
        title: "Verify Your Company",
        statusChip: "Compliance Review",
        estimatedTime: "⏱ 5 minutes (8–24h review)",
        description: "Submit required company legal registration and representative documents for Admin review.",
        outcome: "Earn the Verified Employer Badge to build applicant trust and unlock posting capabilities.",
        requirements: [
          "Business registration record (DTI, SEC, or BIR 2303)",
          "Company address and official contact information",
          "Authorized representative ID and proof of authority",
        ],
        actionLabel: "Review Verification Requirements",
        illustrationSrc: "/illustrations/how-it-works/employer/verify.svg",
        illustrationAlt: "Employer submitting business verification records",
      },
      {
        stepNumber: 3,
        title: "Complete Your Company Profile",
        statusChip: "Branding & Profile",
        estimatedTime: "⏱ 5–10 minutes",
        description: "Build a trustworthy public company profile that candidates can review before applying.",
        outcome: "Attract top candidates by showcasing your brand, culture, and benefits.",
        requirements: [
          "Company overview, industry, and size",
          "Logo, cover image, address, and contact details",
          "Work culture, perks, and official website links",
        ],
        actionLabel: "Complete Company Profile",
        illustrationSrc: "/illustrations/how-it-works/employer/profile.svg",
        illustrationAlt: "Employer editing company profile and culture details",
      },
      {
        stepNumber: 4,
        title: "Create a Job Posting",
        statusChip: "Vacancy Publishing",
        estimatedTime: "⏱ 5 minutes per post",
        description: "Publish a complete vacancy with clear responsibilities, qualifications, salary, and employment terms.",
        outcome: "Broadcast open roles to thousands of active, qualified job seekers.",
        requirements: [
          "Job title, description, and required qualifications",
          "Location, work setup, and employment type",
          "Application deadline and custom screening questions",
        ],
        actionLabel: "Post a Job",
        illustrationSrc: "/illustrations/how-it-works/employer/post.svg",
        illustrationAlt: "Employer composing and publishing job posting",
      },
      {
        stepNumber: 5,
        title: "Review and Screen Applicants",
        statusChip: "Applicant Screening",
        estimatedTime: "⏱ Ongoing",
        description: "Evaluate submitted applications and move suitable candidates through the recruitment pipeline.",
        outcome: "Efficiently filter candidates using screening responses, résumés, and profile data.",
        requirements: [
          "Review applicant profiles and attached résumés",
          "Evaluate screening question answers",
          "Update applicant pipeline statuses accurately",
        ],
        actionLabel: "Manage Applicants",
        illustrationSrc: "/illustrations/how-it-works/employer/screen.svg",
        illustrationAlt: "Employer evaluating candidates in recruitment pipeline",
      },
      {
        stepNumber: 6,
        title: "Interview and Select Candidates",
        statusChip: "Hiring & Selection",
        estimatedTime: "⏱ Schedule as needed",
        description: "Coordinate interviews, record decisions, and finalize selection for top applicants.",
        outcome: "Successfully hire verified professionals and close open job vacancies.",
        requirements: [
          "Schedule and communicate interview details",
          "Record interview results and internal notes",
          "Update final hiring or selection status",
        ],
        actionLabel: "Start Employer Registration",
        actionRoute: "/signup?role=employer",
        illustrationSrc: "/illustrations/how-it-works/employer/hire.svg",
        illustrationAlt: "Employer conducting candidate interview and finalizing hire",
      },
    ],
  },
  school: {
    roleKey: "school",
    tabLabel: "School / Institution",
    badgeText: "For Academic Institutions",
    heading: "Manage Courses & Verify Graduate Records",
    introduction: "Register your institution, manage official course offerings, and confirm student educational records.",
    accentColor: "text-amber-600 dark:text-amber-400",
    bgAccent: "bg-amber-50 dark:bg-amber-950/30",
    borderAccent: "border-amber-200 dark:border-amber-800",
    totalOnboardingTime: "~10 mins setup + validation",
    oneSentenceSummary: "Register your school, manage official courses, and verify graduate academic records.",
    finalCtaTitle: "Ready to Register Your Academic Institution?",
    finalCtaSubtitle: "Empower your graduates with verified academic credentials on VOS Sync.",
    finalCtaLabel: "Register Your School",
    finalCtaRoute: "/school-register",
    steps: [
      {
        stepNumber: 1,
        title: "Create Your Account",
        statusChip: "School Sign Up",
        estimatedTime: "⏱ 3 minutes",
        description: "Register the institution through an authorized school administrator or registrar representative.",
        outcome: "Establish your institutional portal and access graduate verification tools.",
        requirements: [
          "Use an official institutional email address",
          "Provide representative contact information",
          "Select School as the account type",
        ],
        actionLabel: "Create School Account",
        actionRoute: "/school-register",
        illustrationSrc: "/illustrations/how-it-works/school/register.svg",
        illustrationAlt: "School representative registering academic institution",
      },
      {
        stepNumber: 2,
        title: "Verify Your School",
        statusChip: "Institutional Validation",
        estimatedTime: "⏱ 5 minutes (8–24h review)",
        description: "Submit institutional accreditation and representative authorization documents for Admin validation.",
        outcome: "Gain official institution status to issue verified graduate records.",
        requirements: [
          "Official registration record (CHED, DepEd, TESDA, or SEC)",
          "School campus address and official contact details",
          "Representative identification and proof of authority",
        ],
        actionLabel: "Review Verification Requirements",
        illustrationSrc: "/illustrations/how-it-works/school/verify.svg",
        illustrationAlt: "School representative submitting accreditation records",
      },
      {
        stepNumber: 3,
        title: "Complete Your School Profile",
        statusChip: "Institutional Branding",
        estimatedTime: "⏱ 5 minutes",
        description: "Add approved institutional details, campus information, and recognizable branding.",
        outcome: "Create a recognizable public presence for prospective students and employers.",
        requirements: [
          "School name, type, overview, and contact information",
          "Logo, cover image, campus address, and website link",
          "Authorized representative maintenance controls",
        ],
        actionLabel: "Complete School Profile",
        illustrationSrc: "/illustrations/how-it-works/school/profile.svg",
        illustrationAlt: "School creating official institutional profile",
      },
      {
        stepNumber: 4,
        title: "Register Courses",
        statusChip: "Catalog Management",
        estimatedTime: "⏱ 10 minutes",
        description: "Create and maintain the official courses, degrees, or vocational programs offered by the institution.",
        outcome: "Maintain a standardized academic catalog for graduate verification matching.",
        requirements: [
          "Use standardized course names and degree codes",
          "Set course status and academic level correctly",
          "Avoid duplicate course record entries",
        ],
        actionLabel: "Manage Courses",
        illustrationSrc: "/illustrations/how-it-works/school/courses.svg",
        illustrationAlt: "School managing course catalog and degree programs",
      },
      {
        stepNumber: 5,
        title: "Manage Students and Graduates",
        statusChip: "Roster Management",
        estimatedTime: "⏱ Ongoing",
        description: "Connect candidate profiles to correct institutional courses and graduation cohorts.",
        outcome: "Maintain accurate graduate rosters and streamline credential verification requests.",
        requirements: [
          "Review submitted school and course claims",
          "Maintain accurate student or graduate associations",
          "Protect education privacy according to access rules",
        ],
        actionLabel: "Manage Student Records",
        illustrationSrc: "/illustrations/how-it-works/school/students.svg",
        illustrationAlt: "School reviewing graduate roster and student claims",
      },
      {
        stepNumber: 6,
        title: "Verify Student or Graduate Records",
        statusChip: "Record Validation",
        estimatedTime: "⏱ 1–2 minutes per request",
        description: "Confirm whether submitted candidate education claims match authorized institutional records.",
        outcome: "Issue tamper-proof verified education badges on candidate profiles.",
        requirements: [
          "Validate candidate identity, degree, and graduation year",
          "Approve records supported by institutional data",
          "Flag mismatches for correction or Admin review",
        ],
        actionLabel: "Start School Registration",
        actionRoute: "/school-register",
        illustrationSrc: "/illustrations/how-it-works/school/records.svg",
        illustrationAlt: "School issuing verified education badge for graduate",
      },
    ],
  },
};

export const FAQ_ITEMS: FaqItem[] = [
  {
    id: "faq-1",
    question: "Is registration on VOS Sync completely free?",
    answer: "Yes! Creating an account as an Employee or Job Seeker is 100% free. Employer and School accounts also include free registration and verification setup.",
    category: "general",
  },
  {
    id: "faq-2",
    question: "How long does company or identity verification take?",
    answer: "Verification reviews are typically processed by our compliance team within 8 to 24 hours after document submission.",
    category: "general",
  },
  {
    id: "faq-3",
    question: "Can an account have multiple roles or change roles later?",
    answer: "Each account is registered under a specific role (Employee, Employer, or School) to ensure privacy and security. Additional role access can be requested through support.",
    category: "general",
  },
  {
    id: "faq-4",
    question: "What documents are required for Employer registration?",
    answer: "Employers need a valid business registration (DTI, SEC, or BIR Form 2303), company proof of address, and representative identification.",
    category: "employer",
  },
  {
    id: "faq-5",
    question: "How do verified education badges work for graduates?",
    answer: "When a student claims a degree, the partner school receives a verification request to confirm graduation records, producing a tamper-proof verified badge.",
    category: "school",
  },
];
